// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBP5M9LE0zhj2DfCe_PDpFGMmm5DCV48A',
    appId: '1:57349243665:web:0cc108a30cdf65e357c2b0',
    messagingSenderId: '57349243665',
    projectId: 'docinzo-c5c51',
    authDomain: 'docinzo-c5c51.firebaseapp.com',
    storageBucket: 'docinzo-c5c51.appspot.com',
    measurementId: 'G-37PKCT7P68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1e8ukdlfIDBT-mBBfILbqnB0ZyE1iDK4',
    appId: '1:57349243665:android:cde199ba69c9eaed57c2b0',
    messagingSenderId: '57349243665',
    projectId: 'docinzo-c5c51',
    storageBucket: 'docinzo-c5c51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0giRwwpGAjjc4IA-WeHSgmYbAot_xsw',
    appId: '1:57349243665:ios:0569b67d7592e00a57c2b0',
    messagingSenderId: '57349243665',
    projectId: 'docinzo-c5c51',
    storageBucket: 'docinzo-c5c51.appspot.com',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0giRwwpGAjjc4IA-WeHSgmYbAot_xsw',
    appId: '1:57349243665:ios:4417ecc51bfa23fb57c2b0',
    messagingSenderId: '57349243665',
    projectId: 'docinzo-c5c51',
    storageBucket: 'docinzo-c5c51.appspot.com',
    iosBundleId: 'com.example.doctor.RunnerTests',
  );
}
